version: '3.8'
services:
  postgres:
    image: postgres:13
    env_file:
      - .env

  redis:
    image: redis:7.0-rc3-alpine3.15
    env_file: .env
    command: redis-server
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A test_task worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A test_task beat -l info
    env_file:
      - .env
    depends_on:
      - redis
